### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by technomancy** [kstep/scheme.lua#1]
Hello.

I'm interested in using this code in my OSS game: https://gitlab.com/technomancy/bussard/

However, I noticed it is missing a license. Could you add one to the code? If it's GPL-compatible that would be super. Thanks.

**Comment by technomancy** [comment]
Hey, any chance you could indicate a license on this? It would be nice if I could use this instead of implementing my own Scheme from scratch; thanks.

**Comment by kstep** [comment]
The project was made for fun, so I never thought about licensing. You may consider it free to use. Like maybe MIT or even WTFPL. Anyway, you are free to use it in any way you want.

**Comment by technomancy** [comment]
Thanks; I appreciate it! Cheers.
